trigger:
- main
pool: Todo_Microservice_Agent_Pool

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Himanshu_service'
    backendAzureRmOverrideSubscriptionID: '925c3861-e9e3-43c1-8a0c-d6faefd4a05a'
    backendAzureRmResourceGroupName: 'Brijendra_RG'
    backendAzureRmStorageAccountName: 'brijendrastorgae'
    backendAzureRmContainerName: 'brijendracontainer'
    backendAzureRmKey: 'terrafromstate'
